//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMetier
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MetierPM")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Personne", Namespace="http://schemas.datacontract.org/2004/07/MetierPM.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceMetier.Etudiant))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceMetier.Professeur))]
    public partial class Personne : object
    {
        
        private System.DateTime DateCreationField;
        
        private System.Nullable<System.DateTime> DateModificationField;
        
        private string EmailField;
        
        private int IdField;
        
        private string NomField;
        
        private string PasswordField;
        
        private string PrenomField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreation
        {
            get
            {
                return this.DateCreationField;
            }
            set
            {
                this.DateCreationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateModification
        {
            get
            {
                return this.DateModificationField;
            }
            set
            {
                this.DateModificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom
        {
            get
            {
                return this.PrenomField;
            }
            set
            {
                this.PrenomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Etudiant", Namespace="http://schemas.datacontract.org/2004/07/MetierPM.Model")]
    public partial class Etudiant : ServiceMetier.Personne
    {
        
        private System.DateTime DateNaissanceField;
        
        private ServiceMetier.Filiere FiliereField;
        
        private int IdFiliereField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateNaissance
        {
            get
            {
                return this.DateNaissanceField;
            }
            set
            {
                this.DateNaissanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceMetier.Filiere Filiere
        {
            get
            {
                return this.FiliereField;
            }
            set
            {
                this.FiliereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFiliere
        {
            get
            {
                return this.IdFiliereField;
            }
            set
            {
                this.IdFiliereField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Professeur", Namespace="http://schemas.datacontract.org/2004/07/MetierPM.Model")]
    public partial class Professeur : ServiceMetier.Personne
    {
        
        private string AutresInformationsField;
        
        private string SpecialiteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutresInformations
        {
            get
            {
                return this.AutresInformationsField;
            }
            set
            {
                this.AutresInformationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Specialite
        {
            get
            {
                return this.SpecialiteField;
            }
            set
            {
                this.SpecialiteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filiere", Namespace="http://schemas.datacontract.org/2004/07/MetierPM.Model")]
    public partial class Filiere : object
    {
        
        private ServiceMetier.Departement DepartementField;
        
        private int IdField;
        
        private int IdDepartementField;
        
        private string NomField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceMetier.Departement Departement
        {
            get
            {
                return this.DepartementField;
            }
            set
            {
                this.DepartementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepartement
        {
            get
            {
                return this.IdDepartementField;
            }
            set
            {
                this.IdDepartementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Departement", Namespace="http://schemas.datacontract.org/2004/07/MetierPM.Model")]
    public partial class Departement : object
    {
        
        private ServiceMetier.Filiere[] FilieresField;
        
        private int IdField;
        
        private string NomField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceMetier.Filiere[] Filieres
        {
            get
            {
                return this.FilieresField;
            }
            set
            {
                this.FilieresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom
        {
            get
            {
                return this.NomField;
            }
            set
            {
                this.NomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commentaire", Namespace="http://schemas.datacontract.org/2004/07/MetierPM.Model")]
    public partial class Commentaire : object
    {
        
        private string ContenuField;
        
        private System.DateTime DateField;
        
        private bool EstReponduField;
        
        private ServiceMetier.Etudiant EtudiantField;
        
        private ServiceMetier.Professeur ExpertReponseField;
        
        private int IdField;
        
        private string ReponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contenu
        {
            get
            {
                return this.ContenuField;
            }
            set
            {
                this.ContenuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstRepondu
        {
            get
            {
                return this.EstReponduField;
            }
            set
            {
                this.EstReponduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceMetier.Etudiant Etudiant
        {
            get
            {
                return this.EtudiantField;
            }
            set
            {
                this.EtudiantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceMetier.Professeur ExpertReponse
        {
            get
            {
                return this.ExpertReponseField;
            }
            set
            {
                this.ExpertReponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reponse
        {
            get
            {
                return this.ReponseField;
            }
            set
            {
                this.ReponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Memoire", Namespace="http://schemas.datacontract.org/2004/07/MetierPM.Model")]
    public partial class Memoire : object
    {
        
        private System.DateTime DateSoutenanceField;
        
        private ServiceMetier.Professeur EncadrantField;
        
        private ServiceMetier.Etudiant EtudiantField;
        
        private int IdField;
        
        private int IdEtudiantField;
        
        private int IdProfesseurField;
        
        private string ResumeField;
        
        private string TitreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSoutenance
        {
            get
            {
                return this.DateSoutenanceField;
            }
            set
            {
                this.DateSoutenanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceMetier.Professeur Encadrant
        {
            get
            {
                return this.EncadrantField;
            }
            set
            {
                this.EncadrantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceMetier.Etudiant Etudiant
        {
            get
            {
                return this.EtudiantField;
            }
            set
            {
                this.EtudiantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEtudiant
        {
            get
            {
                return this.IdEtudiantField;
            }
            set
            {
                this.IdEtudiantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProfesseur
        {
            get
            {
                return this.IdProfesseurField;
            }
            set
            {
                this.IdProfesseurField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resume
        {
            get
            {
                return this.ResumeField;
            }
            set
            {
                this.ResumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titre
        {
            get
            {
                return this.TitreField;
            }
            set
            {
                this.TitreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jury", Namespace="http://schemas.datacontract.org/2004/07/MetierPM.Model")]
    public partial class Jury : object
    {
        
        private int IdField;
        
        private ServiceMetier.Memoire[] MemoiresField;
        
        private ServiceMetier.Professeur ProfesseurField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceMetier.Memoire[] Memoires
        {
            get
            {
                return this.MemoiresField;
            }
            set
            {
                this.MemoiresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceMetier.Professeur Professeur
        {
            get
            {
                return this.ProfesseurField;
            }
            set
            {
                this.ProfesseurField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://schemas.datacontract.org/2004/07/MetierPM.Model")]
    public partial class Token : object
    {
        
        private string AccessTokenField;
        
        private int IdField;
        
        private string RefreshTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefreshToken
        {
            get
            {
                return this.RefreshTokenField;
            }
            set
            {
                this.RefreshTokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JwtSettings", Namespace="http://schemas.datacontract.org/2004/07/MetierPM.Model")]
    public partial class JwtSettings : object
    {
        
        private int AccessTokenExpirationMinutesField;
        
        private string AudienceField;
        
        private int IdField;
        
        private string IssuerField;
        
        private int RefreshTokenExpirationDaysField;
        
        private string SecretKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccessTokenExpirationMinutes
        {
            get
            {
                return this.AccessTokenExpirationMinutesField;
            }
            set
            {
                this.AccessTokenExpirationMinutesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Audience
        {
            get
            {
                return this.AudienceField;
            }
            set
            {
                this.AudienceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issuer
        {
            get
            {
                return this.IssuerField;
            }
            set
            {
                this.IssuerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RefreshTokenExpirationDays
        {
            get
            {
                return this.RefreshTokenExpirationDaysField;
            }
            set
            {
                this.RefreshTokenExpirationDaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretKey
        {
            get
            {
                return this.SecretKeyField;
            }
            set
            {
                this.SecretKeyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMetier.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServiceMetier.CompositeType> GetDataUsingDataContractAsync(ServiceMetier.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidatePersonne", ReplyAction="http://tempuri.org/IService1/ValidatePersonneResponse")]
        System.Threading.Tasks.Task<bool> ValidatePersonneAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterPersonne", ReplyAction="http://tempuri.org/IService1/RegisterPersonneResponse")]
        System.Threading.Tasks.Task RegisterPersonneAsync(ServiceMetier.Personne newPersonne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEtudiant", ReplyAction="http://tempuri.org/IService1/AddEtudiantResponse")]
        System.Threading.Tasks.Task AddEtudiantAsync(ServiceMetier.Etudiant etudiant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEtudiantById", ReplyAction="http://tempuri.org/IService1/GetEtudiantByIdResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Etudiant> GetEtudiantByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllEtudiants", ReplyAction="http://tempuri.org/IService1/GetAllEtudiantsResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Etudiant[]> GetAllEtudiantsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateEtudiant", ReplyAction="http://tempuri.org/IService1/UpdateEtudiantResponse")]
        System.Threading.Tasks.Task UpdateEtudiantAsync(ServiceMetier.Etudiant etudiant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteEtudiant", ReplyAction="http://tempuri.org/IService1/DeleteEtudiantResponse")]
        System.Threading.Tasks.Task DeleteEtudiantAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProfesseur", ReplyAction="http://tempuri.org/IService1/AddProfesseurResponse")]
        System.Threading.Tasks.Task AddProfesseurAsync(ServiceMetier.Professeur professeur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProfesseurById", ReplyAction="http://tempuri.org/IService1/GetProfesseurByIdResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Professeur> GetProfesseurByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllProfesseurs", ReplyAction="http://tempuri.org/IService1/GetAllProfesseursResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Professeur[]> GetAllProfesseursAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProfesseur", ReplyAction="http://tempuri.org/IService1/UpdateProfesseurResponse")]
        System.Threading.Tasks.Task UpdateProfesseurAsync(ServiceMetier.Professeur professeur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProfesseur", ReplyAction="http://tempuri.org/IService1/DeleteProfesseurResponse")]
        System.Threading.Tasks.Task DeleteProfesseurAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPersonne", ReplyAction="http://tempuri.org/IService1/AddPersonneResponse")]
        System.Threading.Tasks.Task AddPersonneAsync(ServiceMetier.Personne personne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPersonneById", ReplyAction="http://tempuri.org/IService1/GetPersonneByIdResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Personne> GetPersonneByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPersonnes", ReplyAction="http://tempuri.org/IService1/GetAllPersonnesResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Personne[]> GetAllPersonnesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePersonne", ReplyAction="http://tempuri.org/IService1/UpdatePersonneResponse")]
        System.Threading.Tasks.Task UpdatePersonneAsync(ServiceMetier.Personne personne);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePersonne", ReplyAction="http://tempuri.org/IService1/DeletePersonneResponse")]
        System.Threading.Tasks.Task DeletePersonneAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCommentaire", ReplyAction="http://tempuri.org/IService1/AddCommentaireResponse")]
        System.Threading.Tasks.Task AddCommentaireAsync(ServiceMetier.Commentaire commentaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCommentaireById", ReplyAction="http://tempuri.org/IService1/GetCommentaireByIdResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Commentaire> GetCommentaireByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllCommentaires", ReplyAction="http://tempuri.org/IService1/GetAllCommentairesResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Commentaire[]> GetAllCommentairesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCommentaire", ReplyAction="http://tempuri.org/IService1/UpdateCommentaireResponse")]
        System.Threading.Tasks.Task UpdateCommentaireAsync(ServiceMetier.Commentaire commentaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCommentaire", ReplyAction="http://tempuri.org/IService1/DeleteCommentaireResponse")]
        System.Threading.Tasks.Task DeleteCommentaireAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddDepartement", ReplyAction="http://tempuri.org/IService1/AddDepartementResponse")]
        System.Threading.Tasks.Task AddDepartementAsync(ServiceMetier.Departement departement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDepartementById", ReplyAction="http://tempuri.org/IService1/GetDepartementByIdResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Departement> GetDepartementByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllDepartements", ReplyAction="http://tempuri.org/IService1/GetAllDepartementsResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Departement[]> GetAllDepartementsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDepartement", ReplyAction="http://tempuri.org/IService1/UpdateDepartementResponse")]
        System.Threading.Tasks.Task UpdateDepartementAsync(ServiceMetier.Departement departement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteDepartement", ReplyAction="http://tempuri.org/IService1/DeleteDepartementResponse")]
        System.Threading.Tasks.Task DeleteDepartementAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFiliere", ReplyAction="http://tempuri.org/IService1/AddFiliereResponse")]
        System.Threading.Tasks.Task AddFiliereAsync(ServiceMetier.Filiere filiere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFiliereById", ReplyAction="http://tempuri.org/IService1/GetFiliereByIdResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Filiere> GetFiliereByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFilieres", ReplyAction="http://tempuri.org/IService1/GetAllFilieresResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Filiere[]> GetAllFilieresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateFiliere", ReplyAction="http://tempuri.org/IService1/UpdateFiliereResponse")]
        System.Threading.Tasks.Task UpdateFiliereAsync(ServiceMetier.Filiere filiere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFiliere", ReplyAction="http://tempuri.org/IService1/DeleteFiliereResponse")]
        System.Threading.Tasks.Task DeleteFiliereAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddMemoire", ReplyAction="http://tempuri.org/IService1/AddMemoireResponse")]
        System.Threading.Tasks.Task AddMemoireAsync(ServiceMetier.Memoire memoire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMemoireById", ReplyAction="http://tempuri.org/IService1/GetMemoireByIdResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Memoire> GetMemoireByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMemoires", ReplyAction="http://tempuri.org/IService1/GetAllMemoiresResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Memoire[]> GetAllMemoiresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMemoire", ReplyAction="http://tempuri.org/IService1/UpdateMemoireResponse")]
        System.Threading.Tasks.Task UpdateMemoireAsync(ServiceMetier.Memoire memoire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMemoire", ReplyAction="http://tempuri.org/IService1/DeleteMemoireResponse")]
        System.Threading.Tasks.Task DeleteMemoireAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddJury", ReplyAction="http://tempuri.org/IService1/AddJuryResponse")]
        System.Threading.Tasks.Task AddJuryAsync(ServiceMetier.Jury jury);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJuryById", ReplyAction="http://tempuri.org/IService1/GetJuryByIdResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Jury> GetJuryByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllJuries", ReplyAction="http://tempuri.org/IService1/GetAllJuriesResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Jury[]> GetAllJuriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateJury", ReplyAction="http://tempuri.org/IService1/UpdateJuryResponse")]
        System.Threading.Tasks.Task UpdateJuryAsync(ServiceMetier.Jury jury);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteJury", ReplyAction="http://tempuri.org/IService1/DeleteJuryResponse")]
        System.Threading.Tasks.Task DeleteJuryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToken", ReplyAction="http://tempuri.org/IService1/AddTokenResponse")]
        System.Threading.Tasks.Task AddTokenAsync(ServiceMetier.Token token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTokenById", ReplyAction="http://tempuri.org/IService1/GetTokenByIdResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Token> GetTokenByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTokens", ReplyAction="http://tempuri.org/IService1/GetAllTokensResponse")]
        System.Threading.Tasks.Task<ServiceMetier.Token[]> GetAllTokensAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateToken", ReplyAction="http://tempuri.org/IService1/UpdateTokenResponse")]
        System.Threading.Tasks.Task UpdateTokenAsync(ServiceMetier.Token token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteToken", ReplyAction="http://tempuri.org/IService1/DeleteTokenResponse")]
        System.Threading.Tasks.Task DeleteTokenAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddJwtSettings", ReplyAction="http://tempuri.org/IService1/AddJwtSettingsResponse")]
        System.Threading.Tasks.Task AddJwtSettingsAsync(ServiceMetier.JwtSettings jwtSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJwtSettingsById", ReplyAction="http://tempuri.org/IService1/GetJwtSettingsByIdResponse")]
        System.Threading.Tasks.Task<ServiceMetier.JwtSettings> GetJwtSettingsByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllJwtSettings", ReplyAction="http://tempuri.org/IService1/GetAllJwtSettingsResponse")]
        System.Threading.Tasks.Task<ServiceMetier.JwtSettings[]> GetAllJwtSettingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateJwtSettings", ReplyAction="http://tempuri.org/IService1/UpdateJwtSettingsResponse")]
        System.Threading.Tasks.Task UpdateJwtSettingsAsync(ServiceMetier.JwtSettings jwtSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteJwtSettings", ReplyAction="http://tempuri.org/IService1/DeleteJwtSettingsResponse")]
        System.Threading.Tasks.Task DeleteJwtSettingsAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IService1Channel : ServiceMetier.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceMetier.IService1>, ServiceMetier.IService1
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.CompositeType> GetDataUsingDataContractAsync(ServiceMetier.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Threading.Tasks.Task<bool> ValidatePersonneAsync(string email, string password)
        {
            return base.Channel.ValidatePersonneAsync(email, password);
        }
        
        public System.Threading.Tasks.Task RegisterPersonneAsync(ServiceMetier.Personne newPersonne)
        {
            return base.Channel.RegisterPersonneAsync(newPersonne);
        }
        
        public System.Threading.Tasks.Task AddEtudiantAsync(ServiceMetier.Etudiant etudiant)
        {
            return base.Channel.AddEtudiantAsync(etudiant);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Etudiant> GetEtudiantByIdAsync(int id)
        {
            return base.Channel.GetEtudiantByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Etudiant[]> GetAllEtudiantsAsync()
        {
            return base.Channel.GetAllEtudiantsAsync();
        }
        
        public System.Threading.Tasks.Task UpdateEtudiantAsync(ServiceMetier.Etudiant etudiant)
        {
            return base.Channel.UpdateEtudiantAsync(etudiant);
        }
        
        public System.Threading.Tasks.Task DeleteEtudiantAsync(int id)
        {
            return base.Channel.DeleteEtudiantAsync(id);
        }
        
        public System.Threading.Tasks.Task AddProfesseurAsync(ServiceMetier.Professeur professeur)
        {
            return base.Channel.AddProfesseurAsync(professeur);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Professeur> GetProfesseurByIdAsync(int id)
        {
            return base.Channel.GetProfesseurByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Professeur[]> GetAllProfesseursAsync()
        {
            return base.Channel.GetAllProfesseursAsync();
        }
        
        public System.Threading.Tasks.Task UpdateProfesseurAsync(ServiceMetier.Professeur professeur)
        {
            return base.Channel.UpdateProfesseurAsync(professeur);
        }
        
        public System.Threading.Tasks.Task DeleteProfesseurAsync(int id)
        {
            return base.Channel.DeleteProfesseurAsync(id);
        }
        
        public System.Threading.Tasks.Task AddPersonneAsync(ServiceMetier.Personne personne)
        {
            return base.Channel.AddPersonneAsync(personne);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Personne> GetPersonneByIdAsync(int id)
        {
            return base.Channel.GetPersonneByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Personne[]> GetAllPersonnesAsync()
        {
            return base.Channel.GetAllPersonnesAsync();
        }
        
        public System.Threading.Tasks.Task UpdatePersonneAsync(ServiceMetier.Personne personne)
        {
            return base.Channel.UpdatePersonneAsync(personne);
        }
        
        public System.Threading.Tasks.Task DeletePersonneAsync(int id)
        {
            return base.Channel.DeletePersonneAsync(id);
        }
        
        public System.Threading.Tasks.Task AddCommentaireAsync(ServiceMetier.Commentaire commentaire)
        {
            return base.Channel.AddCommentaireAsync(commentaire);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Commentaire> GetCommentaireByIdAsync(int id)
        {
            return base.Channel.GetCommentaireByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Commentaire[]> GetAllCommentairesAsync()
        {
            return base.Channel.GetAllCommentairesAsync();
        }
        
        public System.Threading.Tasks.Task UpdateCommentaireAsync(ServiceMetier.Commentaire commentaire)
        {
            return base.Channel.UpdateCommentaireAsync(commentaire);
        }
        
        public System.Threading.Tasks.Task DeleteCommentaireAsync(int id)
        {
            return base.Channel.DeleteCommentaireAsync(id);
        }
        
        public System.Threading.Tasks.Task AddDepartementAsync(ServiceMetier.Departement departement)
        {
            return base.Channel.AddDepartementAsync(departement);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Departement> GetDepartementByIdAsync(int id)
        {
            return base.Channel.GetDepartementByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Departement[]> GetAllDepartementsAsync()
        {
            return base.Channel.GetAllDepartementsAsync();
        }
        
        public System.Threading.Tasks.Task UpdateDepartementAsync(ServiceMetier.Departement departement)
        {
            return base.Channel.UpdateDepartementAsync(departement);
        }
        
        public System.Threading.Tasks.Task DeleteDepartementAsync(int id)
        {
            return base.Channel.DeleteDepartementAsync(id);
        }
        
        public System.Threading.Tasks.Task AddFiliereAsync(ServiceMetier.Filiere filiere)
        {
            return base.Channel.AddFiliereAsync(filiere);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Filiere> GetFiliereByIdAsync(int id)
        {
            return base.Channel.GetFiliereByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Filiere[]> GetAllFilieresAsync()
        {
            return base.Channel.GetAllFilieresAsync();
        }
        
        public System.Threading.Tasks.Task UpdateFiliereAsync(ServiceMetier.Filiere filiere)
        {
            return base.Channel.UpdateFiliereAsync(filiere);
        }
        
        public System.Threading.Tasks.Task DeleteFiliereAsync(int id)
        {
            return base.Channel.DeleteFiliereAsync(id);
        }
        
        public System.Threading.Tasks.Task AddMemoireAsync(ServiceMetier.Memoire memoire)
        {
            return base.Channel.AddMemoireAsync(memoire);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Memoire> GetMemoireByIdAsync(int id)
        {
            return base.Channel.GetMemoireByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Memoire[]> GetAllMemoiresAsync()
        {
            return base.Channel.GetAllMemoiresAsync();
        }
        
        public System.Threading.Tasks.Task UpdateMemoireAsync(ServiceMetier.Memoire memoire)
        {
            return base.Channel.UpdateMemoireAsync(memoire);
        }
        
        public System.Threading.Tasks.Task DeleteMemoireAsync(int id)
        {
            return base.Channel.DeleteMemoireAsync(id);
        }
        
        public System.Threading.Tasks.Task AddJuryAsync(ServiceMetier.Jury jury)
        {
            return base.Channel.AddJuryAsync(jury);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Jury> GetJuryByIdAsync(int id)
        {
            return base.Channel.GetJuryByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Jury[]> GetAllJuriesAsync()
        {
            return base.Channel.GetAllJuriesAsync();
        }
        
        public System.Threading.Tasks.Task UpdateJuryAsync(ServiceMetier.Jury jury)
        {
            return base.Channel.UpdateJuryAsync(jury);
        }
        
        public System.Threading.Tasks.Task DeleteJuryAsync(int id)
        {
            return base.Channel.DeleteJuryAsync(id);
        }
        
        public System.Threading.Tasks.Task AddTokenAsync(ServiceMetier.Token token)
        {
            return base.Channel.AddTokenAsync(token);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Token> GetTokenByIdAsync(int id)
        {
            return base.Channel.GetTokenByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.Token[]> GetAllTokensAsync()
        {
            return base.Channel.GetAllTokensAsync();
        }
        
        public System.Threading.Tasks.Task UpdateTokenAsync(ServiceMetier.Token token)
        {
            return base.Channel.UpdateTokenAsync(token);
        }
        
        public System.Threading.Tasks.Task DeleteTokenAsync(int id)
        {
            return base.Channel.DeleteTokenAsync(id);
        }
        
        public System.Threading.Tasks.Task AddJwtSettingsAsync(ServiceMetier.JwtSettings jwtSettings)
        {
            return base.Channel.AddJwtSettingsAsync(jwtSettings);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.JwtSettings> GetJwtSettingsByIdAsync(int id)
        {
            return base.Channel.GetJwtSettingsByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceMetier.JwtSettings[]> GetAllJwtSettingsAsync()
        {
            return base.Channel.GetAllJwtSettingsAsync();
        }
        
        public System.Threading.Tasks.Task UpdateJwtSettingsAsync(ServiceMetier.JwtSettings jwtSettings)
        {
            return base.Channel.UpdateJwtSettingsAsync(jwtSettings);
        }
        
        public System.Threading.Tasks.Task DeleteJwtSettingsAsync(int id)
        {
            return base.Channel.DeleteJwtSettingsAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:51321/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
